import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/components/Providers";
import Navbar from "@/components/Navbar";
import { KeyProvider } from "@/context/KeyContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "CV Master",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const apiKey = process.env.OPENAI_API_KEY;

  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <KeyProvider>
          <Providers apiKey={apiKey}>
            <div className="max-w-5xl p-4 mx-auto flex flex-col h-screen gap-4">
              <Navbar />
              <div className="border border-border w-full p-4 rounded-md h-full bg-card">
                {children}
              </div>
            </div>
          </Providers>
        </KeyProvider>
      </body>
    </html>
  );
}
